### ISSUE TITLE
Wallpapers load in debug, but not in release

### ISSUE THREAD

**Issue by pexeixv** [jahirfiquitiva/Frames#262] opened 2023-07-29 03:48 UTC
### Requirements

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

### Frames Version

3.5.6

### Android Version

13

### Device Manufacturer

Nothing

### Device Name

A063

### What happened?

My `json_url` is https://madridista.gavn.in. When I run it in debug mode, the wallpapers load and so do the collections. However, after publishing my app to the Play Store, the wallpapers do not load.

| In debug                                                                                                                     | In release                                                                                                                   |
|------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| ![Screenshot_20230723-192632](https://github.com/jahirfiquitiva/Frames/assets/68476117/7fd1ea90-93c6-4e55-9ab7-51d4e4492a9e) | ![Screenshot_20230729-091121](https://github.com/jahirfiquitiva/Frames/assets/68476117/b6f5d045-6d0c-4af6-a826-d1e8b6981bf7) |

### Reproduction Steps

Setting `json_url` to https://madridista.gavn.in

### Expected behavior

Wallpapers needed to load

### Code and/or Logs

https://github.com/pexeixv/madridista

-----

**Comment by pashapuma** [comment] 2023-07-29 08:03
Yes  for me too. and Frames realise  3.5.6 not work

**Comment by jahirfiquitiva** [comment] 2023-07-29 13:19
## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh/jahirfiquitiva/Frames/issues/262) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jahirfiquitiva/Frames/issues/262">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/262/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/262/pledge.svg">
</picture>
</a>

**Comment by pexeixv** [comment] 2023-07-29 14:21
This issue seems to be an issue with the ''core'' functionality of Frames, rather than anything specific to my app.

**Comment by jahirfiquitiva** [comment] 2023-07-29 14:26
@pexeixv yes, it is an issue with Frames, don't worry. The issue is reproducible with the sample app.

If you would like to fund or support the development effort to resolve the issue, you can do so via Polar:
<a href="https://polar.sh/jahirfiquitiva/Frames/issues/262">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/262/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jahirfiquitiva/Frames/issues/262/pledge.svg">
</picture>
</a>

**Comment by pexeixv** [comment] 2023-07-29 14:49
Is it an intentional bug?

**Comment by jahirfiquitiva** [comment] 2023-07-29 15:04
@pexeixv what do you mean intentional? No bug is intentional, all bugs are unexpected. Why would it be intentional?

**Comment by jahirfiquitiva** [comment] 2023-07-29 15:54
Fixed in v `3.5.7`

**Closed as completed by jahirfiquitiva** 2023-07-29 15:54 UTC
Labels: Type: Bug, Priority: Critical, Status: Completed
